name: Black & Pylint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  black-pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Black & Pylint
        run: |
          python -m pip install black pylint

      - name: Run Black
        run: black .

      - name: Run Pylint
        run: pylint --rcfile=.pylintrc .

